[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
pluto = "8JABYdaQA9jspWE4oFmBNF1LbKS1nyrNGhQHm94iwURi"
[programs.devnet]
pluto = "8JABYdaQA9jspWE4oFmBNF1LbKS1nyrNGhQHm94iwURi"
[programs.localnet]
pluto = "8JABYdaQA9jspWE4oFmBNF1LbKS1nyrNGhQHm94iwURi"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"
#wallet = "~/.config/solana/idx.json"
#wallet = "~/.config/solana/idy.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/check.ts"
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create.ts"
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.ts"
deposit-token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit_token.ts"
withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.ts"
